name: spectra312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.26,<3
  - pyside6>=6.8,<6.10
  - pyqtgraph=0.13.7
  - astropy=7.1.1
  - astroquery=0.4.7
  - pandas=2.2.3
  - requests>=2.32.3,<3
  - pytest=8.4.1
  - pyhdf>=0.11.6
  - pip
  - pip:
    # Add any pure-Python packages here if needed
